nama = input   ("Nama                 : ")
nim = input    ("NIM                  : ")
paralel = input("Kelas Paralel        : ")
TTL = input ("Tempat/Tanggal Lahir : ")
alamat = input ("Alamat               : ")
hobi = input   ("Hobby                : ")
hp = input     ("No. Hp               : ")
print ("\n")

print("INPUT DATA")
print("Nama                 : ", nama)
print("NIM                  : ", nim)
print("Kelas Paralel        : ", paralel)
print("Tempat/Tanggal Lahir : ", TTL)
print("Alamat               : ", alamat)
print("Hobby                : ", hobi)
print("No. Hp               : ", hp)